language: python
python:
  - 3.2
  - 3.3
install:
  - pip install -r requirements.txt
  - pip install coverage==3.7.1 coveralls==0.4.1
script:
  - coverage run manage.py test
  - coverage report --fail-under=100
after_success:
  - coveralls
