language: python
python:
  - 3.3
  - 3.4
install:
  - pip install -r requirements.txt
  - pip install coverage==3.7.1 coveralls==0.4.1 flake8==2.1.0
script:
  - coverage run --branch=false --source=learningprogress manage.py test
  - coverage report --omit=learningprogress/wsgi.py --fail-under=100
  - flake8 --max-line-length=150 learningprogress tests
after_success:
  - coveralls
