language: python
python:
  - 3.2
  - 3.3
install:
  - pip install -r requirements.txt
  - pip install coverage==3.7.1 coveralls==0.4.1 flake8==2.1.0
script:
  - coverage run manage.py test
  - coverage report --fail-under=100
  - flake8 --max-line-length=150 learningprogress tests
after_success:
  - coveralls
