language: python
python:
  - "3.2"
  - "3.3"
install: "pip install -r requirements.txt"
script:
  - "coverage run --source=learningprogress manage.py test"
  - "coverage report -m --fail-under=100 --omit=learningprogress/wsgi.py"
