language: python
python:
  - 3.3
  - 3.4
install:
  - pip install -r requirements.txt
  - pip install coverage==3.7.1 coveralls==0.5 flake8==2.4.0
script:
  - coverage run --source=learningprogress manage.py test
  - coverage report --omit=learningprogress/default_settings.py,learningprogress/wsgi.py --fail-under=100
  - flake8 --max-line-length=150 learningprogress tests
after_success:
  - coveralls
