language: python
sudo: false
cache:
  directories:
    - "$HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python$TRAVIS_PYTHON_VERSION/site-packages/"
    - "$HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/bin/"
python:
  - "3.3"
  - "3.4"
install:
  - "pip install --upgrade --requirement requirements.txt"
  - "pip install --upgrade coverage==4.0a5 coveralls==1.0a2 flake8==2.4.0"
script:
  - "flake8 learningprogress tests"
  - "coverage run manage.py test"
  - "coverage report --fail-under=100"
after_success:
  - "coveralls"
